all: true
check-coverage: true
include: [src/**/*.js]
exclude:
  - src/assets/**
  - src/app/**/fields.js
  - src/app/**/steps.js
report-dir: reports/coverage
statements: 60
branches: 60
functions: 60
lines: 60
watermarks:
  statements:
    - 60
    - 90
  branches:
    - 80
    - 90
  functions:
    - 60
    - 90
  lines:
    - 60
    - 90
